version: '3.9'

services:
  hublocalapi:
    container_name: hublocal-api
    image: 734980421251.dkr.ecr.sa-east-1.amazonaws.com/hublocal:hub-api
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    networks:
      - hublocal-network

  webserver:
    container_name: hublocal-webserver
    image: 734980421251.dkr.ecr.sa-east-1.amazonaws.com/hublocal:hub-webserver
    restart: always
    build:
      context: ./nginx/
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    networks:
      - hublocal-network
    depends_on:
      - hublocalapi

networks:
  hublocal-network: